### ISSUE TITLE
Any reasons not to use the Vagrant image for production?

### ISSUE THREAD

**Issue by epiraces** [harvard-lil/perma#2378] opened 2018-05-28 23:39 UTC
I am interested in running an instance of Perma, I could install from scratch but it seems the Vagrant path may save me some time. Any guidance on the pros/cons would be greatly appreciated.

**Comment by bensteinberg** [comment] 2018-06-21 15:58
Interesting idea! I don't think we can recommend that, as our Vagrant setup was intended specifically as a development environment, is somewhat dated, and in fact, atlas.hashicorp.com, where the box lived, has gone away. We're moving toward a Docker environment for development, and that could be a good basis for a production deployment -- keep an eye out for further development/documentation. At the moment, however, we're deploying to servers running Debian stretch, and managing configuration with SaltStack. We don't have the salt config in the repo; I'd consider adding it if there's any interest.

**Closed by bensteinberg** 2018-06-21 15:58 UTC
