### ISSUE TITLE
Private links not viewable to that institution's registrar user(s)

### ISSUE THREAD

**Issue by bjohnson747** [harvard-lil/perma#2184] opened 2017-12-06 21:45 UTC
A given institutions' private links should be visible to registrar users there, per a registrar user she was unable to view a private link created by a user at the institution.

**Comment by rebeccacremona** [comment] 2017-12-07 15:00
If confidential, can you share details offline? Which link? The code already allows for registrar users to view private links in all folders belonging to their orgs:

https://github.com/harvard-lil/perma/blob/develop/perma_web/perma/models.py#L602

So probably not a bug, I'm guessing, but more likely a UX issue: the user's link is probably in one of their personal folders, and not in an org folder?

Maybe we should, for logged in users, change the appearance of playbacks from personal folders and org folders.

**Comment by rebeccacremona** [comment] 2017-12-07 19:14
Brett says UX is fine; this was a one-time confusion. Accordingly, closing.

**Closed by rebeccacremona** 2017-12-07 19:14 UTC
Labels: UX challenge
