### ISSUE TITLE
Editing Registrar information created new Registrar

### ISSUE THREAD

**Issue by cdemarco** [harvard-lil/perma#1184] opened 2015-10-10 18:44 UTC
I created a new Registrar and then went to edit that registrar's website.  When I did that, it created a duplicate Registrar - one has the original URL and the other has the updated URL
![image](https://cloud.githubusercontent.com/assets/5711415/10412739/717b5f32-6f5d-11e5-972d-d4b1fc0bce96.png)

**Comment by anniejocain** [comment] 2015-11-23 19:27
I can't reproduce this. It is possible to have multiple registrars with the same exact name, email and website. In the screenshot one has a registrar user and the other doesn't. Maybe just a registrar that was created twice? Closing for now.

**Closed by anniejocain** 2015-11-23 19:27 UTC
Labels: bug
