### ISSUE TITLE
Replaying public Facebook posts sometimes fails

### ISSUE THREAD

**Issue by peterk** [harvard-lil/perma#2416] opened 2018-07-14 20:47 UTC
Tried to capture and replay a couple of public Facebook posts. Sometimes, posts with accented characters (e.g. å ä ö in Swedish) does not seem possible to play back after capture (the screenshot works though). Public posts without accented characters seem to work well. Not sure if this was temporary error but looking at my local installation I get the following message in the error log:

```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 95: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pywb/rewrite/html_rewriter.py", line 452, in feed
    HTMLParser.feed(self, string)
  File "/usr/local/lib/python2.7/HTMLParser.py", line 117, in feed
    self.goahead(0)
  File "/usr/local/lib/python2.7/HTMLParser.py", line 161, in goahead
    k = self.parse_starttag(i)
  File "/usr/local/lib/python2.7/HTMLParser.py", line 325, in parse_starttag
    self.handle_startendtag(tag, attrs)
  File "/usr/local/lib/python2.7/site-packages/pywb/rewrite/html_rewriter.py", line 487, in handle_startendtag
    self._rewrite_tag_attrs(tag, attrs)
  File "/usr/local/lib/python2.7/site-packages/pywb/rewrite/html_rewriter.py", line 350, in _rewrite_tag_attrs
    self._write_attr(attr_name, attr_value, empty_attr)
  File "/usr/local/lib/python2.7/site-packages/pywb/rewrite/html_rewriter.py", line 381, in _write_attr
    self.out.write(' ' + name + '="' + value.replace('"', '&quot;') + '"')
```

I tried capturing the following public post without success:

https://www.facebook.com/pkrant/posts/2002889319755215
https://perma.cc/5CBY-38QG

Other open posts seem to work fine:

https://www.facebook.com/pkrant/posts/2003812472996233
https://perma.cc/8ZWJ-5SAW

**Comment by rebeccacremona** [comment] 2018-07-16 13:59
Yikes! That fails rather spectacularly. I can reproduce locally and on our staging tier: the unicode error is real, not transient.

Taking a quick look, it looks like the playback code is equipped to handle unicode within html tags' bodies (see https://perma.cc/866S-RUG8)... but from the stacktrace, evidently not within tags' attributes. 

We are working on a migration to python 3: if this is not resolved as part of that migration, I'll patch  shortly.

Thanks for the report!

**Comment by rebeccacremona** [comment] 2018-07-16 15:38
Modern pywb handles this identically: https://github.com/webrecorder/pywb/blob/master/pywb/rewrite/content_rewriter.py#L300, https://github.com/webrecorder/pywb/blob/master/pywb/rewrite/html_rewriter.py#L473. Yet, WR is not similarly broken. Perhaps because pywb handles both capture and playback....

**Comment by rebeccacremona** [comment] 2018-07-16 15:42
Similar: https://github.com/webrecorder/pywb/commit/9acad278011e7ec6e2b4e2044e137d5d5382c840

**Comment by rebeccacremona** [comment] 2018-07-17 12:57
Thanks, Github, for auto-closing: let's keep this open until I can see it working in production.

**Comment by rebeccacremona** [comment] 2018-07-17 13:18
Recording for further discussion: with this monkeypatch, run in python 2.7,
```
# monkey patch the html rewriter to handle unicode in html attributes
real_write_attr= HTMLRewriterMixin._write_attr
def _write_attr(self, name, value, empty_attr):
    # python2-only handling of unicode html attrs
    # if isinstance(name, str):
    #     name = name.decode('latin-1')
    # if isinstance(value, str):
    #     value = value.decode('latin-1')
    print(name, value)
    real_write_attr(self, name, value, empty_attr)
HTMLRewriterMixin._write_attr = _write_attr
```
We see errors for the following name/value pairs.
```
(u'href', 'http://perma-archives.test:8000/warc/X6HK-V44G/https://www.facebook.com/concernedontariodoctors/photos/another-major-concerned-ontario-doctors\xe2\x80\x99/1331816100285826/')

(u'href', 'http://perma-archives.test:8000/warc/3U9F-K2CE/https://www.facebook.com/pkrant/posts/imponerad-\xc3\xb6ver-all-programvara-som/2002889319755215/')
```
I may look into why the values are str and not unicode at this point.

**Comment by rebeccacremona** [comment] 2018-07-17 14:23
https://perma.cc/5CBY-38QG is now playing back correctly. Thanks again for the report, @peterk!

**Closed by rebeccacremona** 2018-07-17 14:23 UTC
Labels: bug
